---
 - name: Deploy docker-compose
   hosts: ec2
   become: true
   vars:
    image_name: "{{lookup('env','IMAGE_NAME')}}"
    db_user: "{{lookup('env', 'DB_USER')}}"
    db_password: "{{lookup('env','DB_PASSWORD')}}"
   tasks:
    - name: Install docker
      ansible.builtin.yum:
        name: 
          - docker
        update_cache: yes
    - name: Start docker
      ansible.builtin.service:
        name: docker
        state: started
        
    - name: Install docker-compose
      get_url: 
        url : https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: Create app dir
      file:
        path: /myapp
        state: directory
    - name: Copy nginx related files from runner to ec2
      copy: 
        src: nginx
        dest: /myapp/nginx
        
    - name: Copy docker-compose file from runner to ec2
      copy:
        src: docker-compose.yml
        dest: /myapp/docker-compose.yml
      
    - name: Create .env file for docker-compose secrets
      copy:
        dest: /myapp/.env
        content: |
          IMAGE_NAME = {{image_name}}
          DB_USER = {{db_user}}
          DB_PASSWORD = {{db_password}}
      no_log: true

    - name: Run docker-compose
      shell: docker-compose --env-file .env up -d
      args:
        chdir: /myapp